name: "Code Scanning"

on:
  push:
    branches: [ "main" ]

  #watch:
  #  types: [started]

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          VER=$(cat env | awk {'print$2'})
          echo $VER
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Run Trivy vulnerability scanner for lb-exporter-deployment
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ugurozturk99/lp-exporter-deployment:v${{ env.VERSION }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Run Trivy vulnerability scanner for lb-exporter-job
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ugurozturk99/lp-exporter-job:v${{ env.VERSION }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
